# Generated by Django 6.0.1 on 2026-08-03 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, help_text='Earnings per share', max_digits=20, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Price/Earnings ratio', max_digits=12, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=4, help_text='Book value per share', max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Market capitalisation in NGN', max_digits=24, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_class', models.CharField(choices=[('MONEY_MARKET', 'Money Market'), ('FIXED_INCOME', 'Fixed Income'), ('EQUITY', 'Equity'), ('BALANCED', 'Balanced'), ('ETHICAL', 'Ethical/Islamic'), ('REAL_ESTATE', 'Real Estate'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('PRICE', 'Price'), ('YIELD', 'Yield'), ('NAV', 'NAV')], max_length=10)),
                ('threshold', models.DecimalField(decimal_places=6, max_digits=20)),
                ('direction', models.CharField(choices=[('ABOVE', 'Above threshold'), ('BELOW', 'Below threshold')], default='ABOVE', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('last_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.fund')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair', models.CharField(db_index=True, help_text='e.g., USD/NGN, GBP/NGN, EUR/NGN', max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(default='CBN', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['pair', '-date'],
                'unique_together': {('pair', 'date', 'source')},
            },
        ),
        migrations.CreateModel(
            name='AuctionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction_date', models.DateField(db_index=True)),
                ('tenor', models.CharField(help_text='e.g., 91-day, 182-day, 364-day, 10-year', max_length=50)),
                ('offer_size', models.DecimalField(blank=True, decimal_places=2, help_text='Offer size in NGN (billions as published by DMO).', max_digits=20, null=True)),
                ('stop_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Stop rate / marginal rate as published by DMO (percent).', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('instrument', models.ForeignKey(limit_choices_to={'asset_class': 'BOND'}, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='api.instrument')),
            ],
            options={
                'ordering': ['auction_date'],
                'indexes': [models.Index(fields=['auction_date', 'is_active'], name='api_auction_auction_5108cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='NavSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('nav', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_snapshots', to='api.fund')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('fund', 'date')},
            },
        ),
    ]
