# Generated by Django 6.0.1 on 2026-08-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companyprofile_fund_alert_fxrate_auctioncalendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='revenue_history',
            field=models.JSONField(blank=True, default=list, help_text='[{year, revenue_ngn}, ...] display only', null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='asset_class',
            field=models.CharField(choices=[('EQUITY', 'Equity (Stock)'), ('BOND', 'Fixed Income (Bond)'), ('FOREX', 'Foreign Exchange'), ('COMMODITY', 'Commodity'), ('CRYPTO', 'Cryptocurrency'), ('DERIVATIVE', 'Derivative (Options/Futures)'), ('COMMERCIAL_PAPER', 'Commercial Paper (CP)')], max_length=20),
        ),
    ]
