# Generated by Django 6.0.1 on 2026-08-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_companyprofile_revenue_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='api.fund'),
        ),
    ]
