# Generated by Django 6.0.1 on 2026-08-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portfolioitem_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='funds',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to='api.fund'),
        ),
    ]
