# Generated by Django 6.0.1 on 2026-08-04 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mixshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixshare',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mixshare',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mix_shares', to='api.portfolio'),
        ),
    ]
