# Generated by Django 6.0.1 on 2026-08-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ext_link',
            field=models.URLField(blank=True, help_text='External source URL (RSS imports)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_rss',
            field=models.BooleanField(default=False, help_text='Auto-imported from RSS feed'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_analytics_at',
            field=models.DateTimeField(blank=True, help_text='ISO timestamp when user opted into anonymized usage analytics', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_terms_at',
            field=models.DateTimeField(blank=True, help_text='ISO timestamp when user accepted T&C + Privacy Policy', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium subscription tier (Voice Learn + advanced features)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
